language: php
dist: trusty
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
#
#matrix:
#  include:
#    - php: 7.1
#      env:
#        - BUILD_PHAR=true

script:
  - composer run-script build -vvv

deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: build/php-cloudstack-generator.phar
  skip_cleanup: true
  on:
    tags: true
    php: '7.2'