language: php
dist: xenial
sudo: false

php:
  - 7.3
  - 7.4

script:
  - composer run-script build -vvv

deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: build/php-cloudstack-generator.phar
  skip_cleanup: true
  on:
    tags: true
    php: '7.4'