language: php
dist: trusty
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.0
      env:
        - BUILD_PHAR=true

script:
  - if [[ $BUILD_PHAR == 'true' && $TRAVIS_TAG != '' ]]; then composer run-script build -vvv ; fi

deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: build/php-cs.phar
  skip_cleanup: true
  on:
    tags: true
    php: '7.0'