# PHP CloudStack Client generator config prototype

# Any option defined in src/Command/AbstractCommand.php can be defined, excluding the "config" and "env" flag.

# Combining rules:
# - If an option is NOT defined here and NOT defined explicitly at runtime, the default value will be used.  If there is
#   no default value for that option, the command will fail.
# - If an option is defined here but NOT defined explicitly at runtime, the value present here will be used.
# - If an option is defined here AND defined explicitly at runtime, the runtime option will be used in favor of the
#   value defined here.
# - If a value is NOT defined here but is defined explicitly at runtime, the runtime value will be used.

# php_cs_generator must be the root key
php_cs_generator:
  # environment configuration
  environments:
    dev: # Name of this config.  Accessible via the "env" option
      scheme: "http"
      local: # if both fields are defined, will use locally-sourced api and capability json for generation
        list_apis_json: ~
        list_capabilities_json: ~
      remote: # if defined and local is not defined, will attempt to pull api and capability json from host
        host: ~ # dev.ourcloudstack.com
        key: ~ # your api key
        secret: ~ # your api secret
        port: 8080
        http_client:
          class: ~ # any class that implements \GuzzleHttp\ClientInterface
          config:
            allow_redirects: true
            http_errors: true
            verify: false
      apipath: "client/api"
      consolepath: "client/console"
      out: ~ # choose output path
      namespace: "\\MyGreatNamespace"
      # generated composer.json details. any valid composer entries are allowed here, ones that have special treatment are listed below
      # if set to null, will not generate this as a composer package but as raw code files instead.
      composer:
        name: ~ # if left blank, will be created from namespace entry above
        type: ~ # if left blank, will be "library"
        license: ~ # if left blank, will be "MIT"
        description: ~ # if left blank, will have default value containing date of generation and ACS version
        authors: # list of authors to be appended to default author list
        - name: "yourname"
          email: "yourname@email.you"
        require: # dependencies to add to the default list
          "package/name": ">=9000.*"
        autoload: ~ # any additional autoload entries you wish to add
      logging:
        enabled: ~ # if set to false, will prevent any logging code from being placed in the output.
        debug: false # if set to true, increases number of log statements generated
      cache:
        id_prefix: ~ # if defined, will prepend each cache id with this value
        default_enabled: false # will disable caching for everything except those explicitly defined in "commands"
        default_ttl: 300 # 5 minutes
        commands:
          listZones:
            ttl: 2592000 # 30 days
          listTemplates:
            ttl: "123s" # supports parsing golang duration format strings, equates to 123 seconds
          listVirtualMachines:
            enabled: false # disables caching entirely for this command
    prod:
      remote:
        host: prod.ourcloudstack.com
        port: 8765
        key: ~ # your api key
        secret: ~ # your api secret
  # allows you to extend the classes constructed by this lib with your own class
  # NOTE: Currently only response classes are allowed to be overloaded
  overloaded_classes:
  - name: Tags                  # name of class you are overloading
    overload: MyGreatTagsClass  # fully qualified name of class extending the base class
    swagger: ~ # Name of Swagger definition you have for the class.  This is only used if you are overloading a field on a response object.  The default Swagger definition name will be left in place if you do not provide one of your own.
  - name: ListTemplatesResponse
    overload: \My\Neato\ListTemplatesResponse
    swagger: MyNeatoListTemplatesResponse