# PHP CloudStack Client generator config prototype

# Any option defined in src/Command/AbstractCommand.php can be defined, excluding the "config" and "env" flag.

# Combining rules:
# - If an option is NOT defined here and NOT defined explicitly at runtime, the default value will be used.  If there is
#   no default value for that option, the command will fail.
# - If an option is defined here but NOT defined explicitly at runtime, the value present here will be used.
# - If an option is defined here AND defined explicitly at runtime, the runtime option will be used in favor of the
#   value defined here.
# - If a value is NOT defined here but is defined explicitly at runtime, the runtime value will be used.

# php_cs_generator must be the root key
php_cs_generator:
  # environment configuration
  environments:
    dev: # Name of this config.  Accessible via the "env" option
      scheme: "http"
      host: ~ # dev.ourcloudstack.com
      port: 8080
      apipath: "client/api"
      consolepath: "client/console"
      out: ~ # choose output path
      namespace: "\\MyGreatNamespace"
      key: ~ # your api key
      secret: ~ # your api secret
      logger:
        class: ~ # psr-3 compliant logger instance
        level: ~ #level the environment's logger should be
      http_client:
        class: ~ # any class that implements \GuzzleHttp\ClientInterface
        config:
          allow_redirects: true
          http_errors: true
          verify: false
    prod:
      host: prod.ourcloudstack.com
      port: 8765
      key: ~ # your api key
      secret: ~ # your api secret
  # allows you to extend the classes constructed by this lib with your own class
  overloaded_classes:
    - name: Tags                  # name of class you are overloading
      overload: MyGreatTagsClass  # fully qualified name of class extending the base class
    - name: ListVirtualMachinesRequest
      overload: DoSomethingCrazyRequest